In [1]:
import numpy as np      #Importing numpy library

In [2]:
my_list = [1,2,3,4]
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [4]:
second_list = [5,6,7,8]
two_d_array = np.array([my_list , second_list])
print(two_d_array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
two_d_array.shape

(2, 4)

In [11]:
two_d_array.size

8

In [12]:
two_d_array.dtype

dtype('int32')

In [13]:
#to create a square 2d array with 1's across the diagonal
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.eye(N=3, #No. of rows
M=5,        #No. of columns
k=1)        #index of the diagonal

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [16]:
#to create an array filled with ones
np.ones(shape=[2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros(shape=[2,2])

array([[0., 0.],
       [0., 0.]])

In [22]:
one_d_array = np.array([1,2,3,4,5,6])
one_d_array[1]

2

In [23]:
one_d_array[3:]

array([4, 5, 6])

In [25]:
one_d_array[::-1]

array([6, 5, 4, 3, 2, 1])

In [27]:
two_d_array=np.array([one_d_array, one_d_array+6 , one_d_array+12])
print(two_d_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [29]:
two_d_array[1,4]

11

In [30]:
two_d_array[1: , 4:]

array([[11, 12],
       [17, 18]])

In [31]:
two_d_array[::-1 , ::-1]  #reverse both dimensions

array([[18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [33]:
np.reshape(a=two_d_array , newshape=(6,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [34]:
np.ravel(a=two_d_array , order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [35]:
np.ravel(a=two_d_array , order='F')    #Fortran style unraveling

array([ 1,  7, 13,  2,  8, 14,  3,  9, 15,  4, 10, 16,  5, 11, 17,  6, 12,
       18])

In [36]:
two_d_array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [37]:
two_d_array.T       #Transpose - rows to columns, columns to rows

array([[ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17],
       [ 6, 12, 18]])

In [38]:
np.flipud(two_d_array)

array([[13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [41]:
np.fliplr(two_d_array)

array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7],
       [18, 17, 16, 15, 14, 13]])

In [46]:
np.rot90(two_d_array,k=1)    #k is number of 90 degree rotations

array([[ 6, 12, 18],
       [ 5, 11, 17],
       [ 4, 10, 16],
       [ 3,  9, 15],
       [ 2,  8, 14],
       [ 1,  7, 13]])

In [48]:
np.roll(a=two_d_array, 
shift=2,            #shifts elements 2 positions
axis=1)             # in each row

array([[ 5,  6,  1,  2,  3,  4],
       [11, 12,  7,  8,  9, 10],
       [17, 18, 13, 14, 15, 16]])

In [49]:
np.roll(a=two_d_array, 
shift=2)     

array([[17, 18,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16]])

In [50]:
array_to_join = np.array([[10,20,30], [40,50,60], [70,80,90]])
np.concatenate((two_d_array, array_to_join) , axis=1)

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 7,  8,  9, 10, 11, 12, 40, 50, 60],
       [13, 14, 15, 16, 17, 18, 70, 80, 90]])

In [51]:
two_d_array + 100  # adds 100 to each element

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118]])

In [52]:
two_d_array - 100  # subtracts 100 from each element

array([[-99, -98, -97, -96, -95, -94],
       [-93, -92, -91, -90, -89, -88],
       [-87, -86, -85, -84, -83, -82]])

In [53]:
two_d_array ** 2  #square each element

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144],
       [169, 196, 225, 256, 289, 324]])

In [54]:
two_d_array %2 #take modulus of each elemnt

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]], dtype=int32)

In [55]:
small_array1 = np.array([[1,2], [3,4]])
small_array1 + small_array1

array([[2, 4],
       [6, 8]])

In [56]:
small_array1 - small_array1

array([[0, 0],
       [0, 0]])

In [57]:
small_array1 * small_array1

array([[ 1,  4],
       [ 9, 16]])

In [58]:
np.mean(two_d_array)

9.5

In [59]:
np.mean(two_d_array , axis=1) #get mean of each row

array([ 3.5,  9.5, 15.5])

In [60]:
np.std(two_d_array)   #standard deviation

5.188127472091127

In [62]:
np.std(two_d_array, axis =1)   #standard deviation of each column

array([1.70782513, 1.70782513, 1.70782513])

In [63]:
np.sum(two_d_array , axis=1)      #Gives the row sum

array([21, 57, 93])

In [64]:
np.sum(two_d_array , axis=0)      #Gives the column sum

array([21, 24, 27, 30, 33, 36])

In [65]:
np.log(two_d_array)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947],
       [1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527,
        2.48490665],
       [2.56494936, 2.63905733, 2.7080502 , 2.77258872, 2.83321334,
        2.89037176]])

In [66]:
np.sqrt(two_d_array)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        , 4.12310563,
        4.24264069]])

In [67]:
#take the vector dot product of row 0 and row 1
np.dot(two_d_array[0,0:], 
        two_d_array[1,0:])

217

In [68]:
np.dot(small_array1 , small_array1)

array([[ 7, 10],
       [15, 22]])